---
# -----------------------------------------------------------------------------
# Site playbook: migrate VLANs to VXLAN.
# -----------------------------------------------------------------------------

- name: VLAN migration operations
  hosts: network_devices
  gather_facts: false
  vars:
    target_actions:
      - migrate

  roles:
    - network_common
    - migrate_to_vxlan
