---
# -----------------------------------------------------------------------------
# Cisco NXOS defaults
# -----------------------------------------------------------------------------
ansible_network_os: nxos
network_os_family: nxos

network_config_module: cisco.nxos.nxos_config
network_vlans_module: cisco.nxos.nxos_vlans
network_facts_module: cisco.nxos.nxos_facts
network_command_module: cisco.nxos.nxos_command

# NXOS trunk patterns for VLAN pruning
trunk_interface_patterns:
  - "Ethernet[0-9]/[0-9]+"
  - "port-channel[0-9]+"
